name: Fix Formatting

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  format:
    name: Fix Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # 6.0.8
        with:
          version: latest

      - name: Use Node.js 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Generate GitHub token
        id: github-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # 3.1.1
        with:
          client-id: ${{ secrets.GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          gh-token: ${{ steps.github-token.outputs.token }}

      - name: Fix formatting
        run: pnpm fmt

      - name: Reset pnpm-lock.yaml
        shell: bash
        run: git checkout -- pnpm-lock.yaml

      - name: Pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # 8.1.1
        with:
          token: ${{ steps.github-token.outputs.token }}
          title: 'chore(style): fix formatting'
          body: 'Fixes formatting issues in the codebase.'
          commit-message: 'chore(style): fix formatting'
          committer: 'HarperFast <noreply@harperdb.io>'
          branch: fix-formatting
          delete-branch: true
          labels: 'automated'
