name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build RocksDB on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Compile RocksDB
        run: |
          mkdir -p build/rocksdb
          cd vendor/rocksdb-*/
          make static_lib
          cp -r include librocksdb.a ../../build/rocksdb
      
      - name: Cache RocksDB
        uses: actions/cache@v4
        with:
          path: build/rocksdb
          key: ${{ runner.os }}-rocksdb-${{ hashFiles('vendor/rocksdb-*/**') }}

  test:
    name: Test on Node.js ${{ matrix.node }}${{ matrix.node == '22' && ', Bun,' || '' }} and ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Bun
        if: ${{ matrix.node == '22' }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Lint
        run: pnpm lint

      - name: Restore RocksDB cache
        uses: actions/cache/restore@v4
        with:
          path: build/rocksdb
          key: ${{ runner.os }}-rocksdb-${{ hashFiles('vendor/rocksdb-*/**') }}
          fail-on-cache-miss: true

      - name: Run tests on Node.js ${{ matrix.node }}
        run: pnpm coverage
      
      - name: Run tests on Bun
        if: ${{ matrix.node == '22' }}
        run: bun coverage
